services:
  postgres:
    container_name: Canamy.DB
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5222:5432
    volumes:
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - canamy

  mailpit:
    container_name: Canamy.MAIL
    image: "axllent/mailpit:latest"
    ports:
      - 1020:1025
      - 8020:8025
    networks:
      - canamy

networks:
  canamy:
    driver: bridge
